services:
  Odiseo\SyliusRbacPlugin\Action\CreateAdministrationRoleViewAction:
    public: true
    arguments:
      - '@Odiseo\SyliusRbacPlugin\Provider\AdminPermissionsProvider'
      - "@twig"

  Odiseo\SyliusRbacPlugin\Action\CreateAdministrationRoleAction:
    public: true
    arguments:
      - "@messenger.default_bus"
      - '@Odiseo\SyliusRbacPlugin\Normalizer\AdministrationRolePermissionNormalizer'
      - "@router"

  Odiseo\SyliusRbacPlugin\Action\UpdateAdministrationRoleViewAction:
    public: true
    arguments:
      - '@Odiseo\SyliusRbacPlugin\Provider\AdminPermissionsProvider'
      - "@odiseo_sylius_rbac_plugin.repository.administration_role"
      - "@twig"
      - "@router"

  Odiseo\SyliusRbacPlugin\Action\UpdateAdministrationRoleAction:
    public: true
    arguments:
      - "@messenger.default_bus"
      - '@Odiseo\SyliusRbacPlugin\Normalizer\AdministrationRolePermissionNormalizer'
      - "@router"
      - "@odiseo_sylius_rbac_plugin.repository.administration_role"
      - "@security.helper"

  Odiseo\SyliusRbacPlugin\Action\DeleteAdministrationRoleAction:
    public: true
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@router"
      - "@odiseo_sylius_rbac_plugin.repository.administration_role"

  Odiseo\SyliusRbacPlugin\Action\BulkDeleteAdministrationRoleAction:
    public: true
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@odiseo_sylius_rbac_plugin.repository.administration_role"
      - "@router"
