services:
  Odiseo\SyliusRbacPlugin\Cli\GrantAccessCommand:
    arguments:
      - '@Odiseo\SyliusRbacPlugin\Cli\Granter\AdministratorAccessGranter'
    tags:
      - { name: console.command, command: odiseo:rbac:grant-access }

  Odiseo\SyliusRbacPlugin\Cli\GrantAccessToGivenAdministratorCommand:
    arguments:
      - '@Odiseo\SyliusRbacPlugin\Cli\Granter\AdministratorAccessGranter'
    tags:
      - {
          name: console.command,
          command: odiseo:rbac:grant-access-to-given-administrator,
        }

  Odiseo\SyliusRbacPlugin\Cli\InstallPluginCommand:
    public: true
    arguments:
      - '@Odiseo\SyliusRbacPlugin\Provider\SyliusSectionsProvider'
      - '@Doctrine\ORM\EntityManagerInterface'
      - "%root_administrator_email%"
    tags:
      - { name: console.command, command: odiseo:rbac:install }

  Odiseo\SyliusRbacPlugin\Cli\NormalizeExistingAdministratorsCommand:
    arguments:
      - "@sylius.repository.admin_user"
      - "@odiseo_sylius_rbac_plugin.repository.administration_role"
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: console.command, command: odiseo:rbac:normalize-administrators }
