imports:
    - { resource: fixtures.yaml }
    - { resource: grids.yaml }
    - { resource: resources.yaml }
    - { resource: sylius_ui.yaml }

parameters:
    root_administrator_email: ''

odiseo_sylius_rbac:
    sylius_sections:
        products_management:
            - sylius_admin_product
        attributes_management:
            - sylius_admin_product_attribute
        inventory_management:
            - sylius_admin_inventory_unit
        taxons_management:
            - sylius_admin_taxon
        associations_management:
            - sylius_admin_product_association_type
            - sylius_admin_product_association
        configuration:
            - sylius_admin_admin_user
            - sylius_admin_channel
            - sylius_admin_country
            - sylius_admin_currency
            - sylius_admin_exchange_rate
            - sylius_admin_locale
            - sylius_admin_payment_method
            - sylius_admin_shipping_category
            - sylius_admin_shipping_method
            - sylius_admin_tax_category
            - sylius_admin_tax_rate
            - sylius_admin_zone
        customers_management:
            - sylius_admin_customer
            - sylius_admin_customer_group
            - sylius_admin_shop_user
        marketing_management:
            - sylius_admin_product_review
            - sylius_admin_promotion
            - sylius_admin_catalog_promotion
        sales_management:
            - sylius_admin_order
            - sylius_admin_payment
            - sylius_admin_shipment
    custom_sections:
        rbac:
            - odiseo_sylius_rbac_plugin
