sylius_resource:
    resources:
        odiseo_sylius_rbac_plugin.administration_role:
            driver: doctrine/orm
            classes:
                model: Odiseo\SyliusRbacPlugin\Entity\AdministrationRole
                interface: Odiseo\SyliusRbacPlugin\Entity\AdministrationRoleInterface
                form: Sylius\Bundle\ResourceBundle\Form\Type\DefaultResourceType
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                factory: Sylius\Component\Resource\Factory\Factory
